#ifndef FUZZY_H
#define FUZZY_H

//--------------------------------------------------------------------------------
// Code generated by jFuzzyLogic
// jFuzzyLogic Version : JFuzzyLogic 3.3 (build 2015-04-09), by Pablo Cingolani 
// jFuzzyLogic creted by Pablo Cingolani
//--------------------------------------------------------------------------------

#include <stdio.h>
#include <stdlib.h>

double ruleAccumulationMethod_max(double defuzzifierValue, double valueToAggregate)     { return ( defuzzifierValue > valueToAggregate ? defuzzifierValue : valueToAggregate ); }

double ruleActivationMethod_min(double degreeOfSupport, double membership)      { return (degreeOfSupport < membership ? degreeOfSupport : membership); }

double ruleConnectionMethod_and(double antecedent1, double antecedent2) { return (antecedent1 < antecedent2 ? antecedent1 : antecedent2); }

class FunctionBlock_game {

        public: 
        // VAR_INPUT
        double Preco;
        double Quantidade_Analises_Positivas;
        double Quantidade_Espectadores;

        // VAR_OUTPUT
        double Indice_Popularidade;

        private: 
        // FUZZIFY Preco
        double Preco_Alto;
        double Preco_Baixo;
        double Preco_Medio;
        double Preco_MuitoAlto;
        double Preco_MuitoBaixo;

        // FUZZIFY Quantidade_Analises_Positivas
        double Quantidade_Analises_Positivas_Alta;
        double Quantidade_Analises_Positivas_Baixa;
        double Quantidade_Analises_Positivas_Media;

        // FUZZIFY Quantidade_Espectadores
        double Quantidade_Espectadores_Alta;
        double Quantidade_Espectadores_Baixa;
        double Quantidade_Espectadores_Media;


        // DEFUZZIFY Indice_Popularidade
        double defuzzify_Indice_Popularidade[1000];


        public:
        FunctionBlock_game();
        void calc();
        void print();

        private:
        void defuzzify();
        void fuzzify();
        void reset();
        double membership_Indice_Popularidade_Alto(double x);
        double membership_Indice_Popularidade_Baixo(double x);
        double membership_Indice_Popularidade_Medio(double x);
        double membership_Preco_Alto(double x);
        double membership_Preco_Baixo(double x);
        double membership_Preco_Medio(double x);
        double membership_Preco_MuitoAlto(double x);
        double membership_Preco_MuitoBaixo(double x);
        double membership_Quantidade_Analises_Positivas_Alta(double x);
        double membership_Quantidade_Analises_Positivas_Baixa(double x);
        double membership_Quantidade_Analises_Positivas_Media(double x);
        double membership_Quantidade_Espectadores_Alta(double x);
        double membership_Quantidade_Espectadores_Baixa(double x);
        double membership_Quantidade_Espectadores_Media(double x);
        void calc_Rules();

};

// Constructor
FunctionBlock_game::FunctionBlock_game() {
        Indice_Popularidade = 0.0;
}

// Calculate function block
void FunctionBlock_game::calc() {
        reset();
        fuzzify();
        calc_Rules();
        defuzzify();
}

// RULEBLOCK Rules
void FunctionBlock_game::calc_Rules() {
        // RULE 1 : IF ((Quantidade_Analises_Positivas IS Baixa) AND (Preco IS MuitoBaixo)) AND (Quantidade_Espectadores IS Baixa) THEN Indice_Popularidade IS Baixo;
        double degreeOfSupport_1 = 1.0 * ( ruleConnectionMethod_and(ruleConnectionMethod_and(Quantidade_Analises_Positivas_Baixa , Preco_MuitoBaixo) , Quantidade_Espectadores_Baixa) );
        if( degreeOfSupport_1 > 0 ) {
                for (int i = 0 ; i < 1000 ; i++ ) {
                        double x = 0.0 + i * 0.1;
                        double membership = membership_Indice_Popularidade_Baixo(x);
                        double y = ruleActivationMethod_min( degreeOfSupport_1 , membership );       
                        defuzzify_Indice_Popularidade[i] += ruleAccumulationMethod_max( defuzzify_Indice_Popularidade[i], y );
                }
        }

        // RULE 2 : IF ((Quantidade_Analises_Positivas IS Baixa) AND (Preco IS Baixo)) AND (Quantidade_Espectadores IS Baixa) THEN Indice_Popularidade IS Baixo;
        double degreeOfSupport_2 = 1.0 * ( ruleConnectionMethod_and(ruleConnectionMethod_and(Quantidade_Analises_Positivas_Baixa , Preco_Baixo) , Quantidade_Espectadores_Baixa) );
        if( degreeOfSupport_2 > 0 ) {
                for (int i = 0 ; i < 1000 ; i++ ) {
                        double x = 0.0 + i * 0.1;
                        double membership = membership_Indice_Popularidade_Baixo(x);
                        double y = ruleActivationMethod_min( degreeOfSupport_2 , membership );       
                        defuzzify_Indice_Popularidade[i] += ruleAccumulationMethod_max( defuzzify_Indice_Popularidade[i], y );
                }
        }

        // RULE 3 : IF ((Quantidade_Analises_Positivas IS Baixa) AND (Preco IS Medio)) AND (Quantidade_Espectadores IS Baixa) THEN Indice_Popularidade IS Medio;
        double degreeOfSupport_3 = 1.0 * ( ruleConnectionMethod_and(ruleConnectionMethod_and(Quantidade_Analises_Positivas_Baixa , Preco_Medio) , Quantidade_Espectadores_Baixa) );
        if( degreeOfSupport_3 > 0 ) {
                for (int i = 0 ; i < 1000 ; i++ ) {
                        double x = 0.0 + i * 0.1;
                        double membership = membership_Indice_Popularidade_Medio(x);
                        double y = ruleActivationMethod_min( degreeOfSupport_3 , membership );       
                        defuzzify_Indice_Popularidade[i] += ruleAccumulationMethod_max( defuzzify_Indice_Popularidade[i], y );
                }
        }

        // RULE 4 : IF ((Quantidade_Analises_Positivas IS Baixa) AND (Preco IS Alto)) AND (Quantidade_Espectadores IS Baixa) THEN Indice_Popularidade IS Baixo;
        double degreeOfSupport_4 = 1.0 * ( ruleConnectionMethod_and(ruleConnectionMethod_and(Quantidade_Analises_Positivas_Baixa , Preco_Alto) , Quantidade_Espectadores_Baixa) );
        if( degreeOfSupport_4 > 0 ) {
                for (int i = 0 ; i < 1000 ; i++ ) {
                        double x = 0.0 + i * 0.1;
                        double membership = membership_Indice_Popularidade_Baixo(x);
                        double y = ruleActivationMethod_min( degreeOfSupport_4 , membership );       
                        defuzzify_Indice_Popularidade[i] += ruleAccumulationMethod_max( defuzzify_Indice_Popularidade[i], y );
                }
        }

        // RULE 5 : IF ((Quantidade_Analises_Positivas IS Baixa) AND (Preco IS MuitoAlto)) AND (Quantidade_Espectadores IS Baixa) THEN Indice_Popularidade IS Baixo;
        double degreeOfSupport_5 = 1.0 * ( ruleConnectionMethod_and(ruleConnectionMethod_and(Quantidade_Analises_Positivas_Baixa , Preco_MuitoAlto) , Quantidade_Espectadores_Baixa) );
        if( degreeOfSupport_5 > 0 ) {
                for (int i = 0 ; i < 1000 ; i++ ) {
                        double x = 0.0 + i * 0.1;
                        double membership = membership_Indice_Popularidade_Baixo(x);
                        double y = ruleActivationMethod_min( degreeOfSupport_5 , membership );       
                        defuzzify_Indice_Popularidade[i] += ruleAccumulationMethod_max( defuzzify_Indice_Popularidade[i], y );
                }
        }

        // RULE 6 : IF ((Quantidade_Analises_Positivas IS Baixa) AND (Preco IS MuitoBaixo)) AND (Quantidade_Espectadores IS Media) THEN Indice_Popularidade IS Baixo;
        double degreeOfSupport_6 = 1.0 * ( ruleConnectionMethod_and(ruleConnectionMethod_and(Quantidade_Analises_Positivas_Baixa , Preco_MuitoBaixo) , Quantidade_Espectadores_Media) );
        if( degreeOfSupport_6 > 0 ) {
                for (int i = 0 ; i < 1000 ; i++ ) {
                        double x = 0.0 + i * 0.1;
                        double membership = membership_Indice_Popularidade_Baixo(x);
                        double y = ruleActivationMethod_min( degreeOfSupport_6 , membership );       
                        defuzzify_Indice_Popularidade[i] += ruleAccumulationMethod_max( defuzzify_Indice_Popularidade[i], y );
                }
        }

        // RULE 7 : IF ((Quantidade_Analises_Positivas IS Baixa) AND (Preco IS Baixo)) AND (Quantidade_Espectadores IS Media) THEN Indice_Popularidade IS Medio;
        double degreeOfSupport_7 = 1.0 * ( ruleConnectionMethod_and(ruleConnectionMethod_and(Quantidade_Analises_Positivas_Baixa , Preco_Baixo) , Quantidade_Espectadores_Media) );
        if( degreeOfSupport_7 > 0 ) {
                for (int i = 0 ; i < 1000 ; i++ ) {
                        double x = 0.0 + i * 0.1;
                        double membership = membership_Indice_Popularidade_Medio(x);
                        double y = ruleActivationMethod_min( degreeOfSupport_7 , membership );       
                        defuzzify_Indice_Popularidade[i] += ruleAccumulationMethod_max( defuzzify_Indice_Popularidade[i], y );
                }
        }

        // RULE 8 : IF ((Quantidade_Analises_Positivas IS Baixa) AND (Preco IS Medio)) AND (Quantidade_Espectadores IS Media) THEN Indice_Popularidade IS Medio;
        double degreeOfSupport_8 = 1.0 * ( ruleConnectionMethod_and(ruleConnectionMethod_and(Quantidade_Analises_Positivas_Baixa , Preco_Medio) , Quantidade_Espectadores_Media) );
        if( degreeOfSupport_8 > 0 ) {
                for (int i = 0 ; i < 1000 ; i++ ) {
                        double x = 0.0 + i * 0.1;
                        double membership = membership_Indice_Popularidade_Medio(x);
                        double y = ruleActivationMethod_min( degreeOfSupport_8 , membership );       
                        defuzzify_Indice_Popularidade[i] += ruleAccumulationMethod_max( defuzzify_Indice_Popularidade[i], y );
                }
        }

        // RULE 9 : IF ((Quantidade_Analises_Positivas IS Baixa) AND (Preco IS Alto)) AND (Quantidade_Espectadores IS Media) THEN Indice_Popularidade IS Medio;
        double degreeOfSupport_9 = 1.0 * ( ruleConnectionMethod_and(ruleConnectionMethod_and(Quantidade_Analises_Positivas_Baixa , Preco_Alto) , Quantidade_Espectadores_Media) );
        if( degreeOfSupport_9 > 0 ) {
                for (int i = 0 ; i < 1000 ; i++ ) {
                        double x = 0.0 + i * 0.1;
                        double membership = membership_Indice_Popularidade_Medio(x);
                        double y = ruleActivationMethod_min( degreeOfSupport_9 , membership );       
                        defuzzify_Indice_Popularidade[i] += ruleAccumulationMethod_max( defuzzify_Indice_Popularidade[i], y );
                }
        }

        // RULE 10 : IF ((Quantidade_Analises_Positivas IS Baixa) AND (Preco IS MuitoAlto)) AND (Quantidade_Espectadores IS Media) THEN Indice_Popularidade IS Baixo;
        double degreeOfSupport_10 = 1.0 * ( ruleConnectionMethod_and(ruleConnectionMethod_and(Quantidade_Analises_Positivas_Baixa , Preco_MuitoAlto) , Quantidade_Espectadores_Media) );
        if( degreeOfSupport_10 > 0 ) {
                for (int i = 0 ; i < 1000 ; i++ ) {
                        double x = 0.0 + i * 0.1;
                        double membership = membership_Indice_Popularidade_Baixo(x);
                        double y = ruleActivationMethod_min( degreeOfSupport_10 , membership );      
                        defuzzify_Indice_Popularidade[i] += ruleAccumulationMethod_max( defuzzify_Indice_Popularidade[i], y );
                }
        }

        // RULE 11 : IF ((Quantidade_Analises_Positivas IS Baixa) AND (Preco IS MuitoBaixo)) AND (Quantidade_Espectadores IS Alta) THEN Indice_Popularidade IS Baixo;
        double degreeOfSupport_11 = 1.0 * ( ruleConnectionMethod_and(ruleConnectionMethod_and(Quantidade_Analises_Positivas_Baixa , Preco_MuitoBaixo) , Quantidade_Espectadores_Alta) );
        if( degreeOfSupport_11 > 0 ) {
                for (int i = 0 ; i < 1000 ; i++ ) {
                        double x = 0.0 + i * 0.1;
                        double membership = membership_Indice_Popularidade_Baixo(x);
                        double y = ruleActivationMethod_min( degreeOfSupport_11 , membership );      
                        defuzzify_Indice_Popularidade[i] += ruleAccumulationMethod_max( defuzzify_Indice_Popularidade[i], y );
                }
        }

        // RULE 12 : IF ((Quantidade_Analises_Positivas IS Baixa) AND (Preco IS Baixo)) AND (Quantidade_Espectadores IS Alta) THEN Indice_Popularidade IS Medio;
        double degreeOfSupport_12 = 1.0 * ( ruleConnectionMethod_and(ruleConnectionMethod_and(Quantidade_Analises_Positivas_Baixa , Preco_Baixo) , Quantidade_Espectadores_Alta) );
        if( degreeOfSupport_12 > 0 ) {
                for (int i = 0 ; i < 1000 ; i++ ) {
                        double x = 0.0 + i * 0.1;
                        double membership = membership_Indice_Popularidade_Medio(x);
                        double y = ruleActivationMethod_min( degreeOfSupport_12 , membership );      
                        defuzzify_Indice_Popularidade[i] += ruleAccumulationMethod_max( defuzzify_Indice_Popularidade[i], y );
                }
        }

        // RULE 13 : IF ((Quantidade_Analises_Positivas IS Baixa) AND (Preco IS Medio)) AND (Quantidade_Espectadores IS Alta) THEN Indice_Popularidade IS Alto;
        double degreeOfSupport_13 = 1.0 * ( ruleConnectionMethod_and(ruleConnectionMethod_and(Quantidade_Analises_Positivas_Baixa , Preco_Medio) , Quantidade_Espectadores_Alta) );
        if( degreeOfSupport_13 > 0 ) {
                for (int i = 0 ; i < 1000 ; i++ ) {
                        double x = 0.0 + i * 0.1;
                        double membership = membership_Indice_Popularidade_Alto(x);
                        double y = ruleActivationMethod_min( degreeOfSupport_13 , membership );      
                        defuzzify_Indice_Popularidade[i] += ruleAccumulationMethod_max( defuzzify_Indice_Popularidade[i], y );
                }
        }

        // RULE 14 : IF ((Quantidade_Analises_Positivas IS Baixa) AND (Preco IS Alto)) AND (Quantidade_Espectadores IS Alta) THEN Indice_Popularidade IS Medio;
        double degreeOfSupport_14 = 1.0 * ( ruleConnectionMethod_and(ruleConnectionMethod_and(Quantidade_Analises_Positivas_Baixa , Preco_Alto) , Quantidade_Espectadores_Alta) );
        if( degreeOfSupport_14 > 0 ) {
                for (int i = 0 ; i < 1000 ; i++ ) {
                        double x = 0.0 + i * 0.1;
                        double membership = membership_Indice_Popularidade_Medio(x);
                        double y = ruleActivationMethod_min( degreeOfSupport_14 , membership );      
                        defuzzify_Indice_Popularidade[i] += ruleAccumulationMethod_max( defuzzify_Indice_Popularidade[i], y );
                }
        }

        // RULE 15 : IF ((Quantidade_Analises_Positivas IS Baixa) AND (Preco IS MuitoAlto)) AND (Quantidade_Espectadores IS Alta) THEN Indice_Popularidade IS Baixo;
        double degreeOfSupport_15 = 1.0 * ( ruleConnectionMethod_and(ruleConnectionMethod_and(Quantidade_Analises_Positivas_Baixa , Preco_MuitoAlto) , Quantidade_Espectadores_Alta) );
        if( degreeOfSupport_15 > 0 ) {
                for (int i = 0 ; i < 1000 ; i++ ) {
                        double x = 0.0 + i * 0.1;
                        double membership = membership_Indice_Popularidade_Baixo(x);
                        double y = ruleActivationMethod_min( degreeOfSupport_15 , membership );      
                        defuzzify_Indice_Popularidade[i] += ruleAccumulationMethod_max( defuzzify_Indice_Popularidade[i], y );
                }
        }

        // RULE 16 : IF ((Quantidade_Analises_Positivas IS Media) AND (Preco IS MuitoBaixo)) AND (Quantidade_Espectadores IS Baixa) THEN Indice_Popularidade IS Baixo;
        double degreeOfSupport_16 = 1.0 * ( ruleConnectionMethod_and(ruleConnectionMethod_and(Quantidade_Analises_Positivas_Media , Preco_MuitoBaixo) , Quantidade_Espectadores_Baixa) );
        if( degreeOfSupport_16 > 0 ) {
                for (int i = 0 ; i < 1000 ; i++ ) {
                        double x = 0.0 + i * 0.1;
                        double membership = membership_Indice_Popularidade_Baixo(x);
                        double y = ruleActivationMethod_min( degreeOfSupport_16 , membership );      
                        defuzzify_Indice_Popularidade[i] += ruleAccumulationMethod_max( defuzzify_Indice_Popularidade[i], y );
                }
        }

        // RULE 17 : IF ((Quantidade_Analises_Positivas IS Media) AND (Preco IS Baixo)) AND (Quantidade_Espectadores IS Baixa) THEN Indice_Popularidade IS Medio;
        double degreeOfSupport_17 = 1.0 * ( ruleConnectionMethod_and(ruleConnectionMethod_and(Quantidade_Analises_Positivas_Media , Preco_Baixo) , Quantidade_Espectadores_Baixa) );
        if( degreeOfSupport_17 > 0 ) {
                for (int i = 0 ; i < 1000 ; i++ ) {
                        double x = 0.0 + i * 0.1;
                        double membership = membership_Indice_Popularidade_Medio(x);
                        double y = ruleActivationMethod_min( degreeOfSupport_17 , membership );      
                        defuzzify_Indice_Popularidade[i] += ruleAccumulationMethod_max( defuzzify_Indice_Popularidade[i], y );
                }
        }

        // RULE 18 : IF ((Quantidade_Analises_Positivas IS Media) AND (Preco IS Medio)) AND (Quantidade_Espectadores IS Baixa) THEN Indice_Popularidade IS Medio;
        double degreeOfSupport_18 = 1.0 * ( ruleConnectionMethod_and(ruleConnectionMethod_and(Quantidade_Analises_Positivas_Media , Preco_Medio) , Quantidade_Espectadores_Baixa) );
        if( degreeOfSupport_18 > 0 ) {
                for (int i = 0 ; i < 1000 ; i++ ) {
                        double x = 0.0 + i * 0.1;
                        double membership = membership_Indice_Popularidade_Medio(x);
                        double y = ruleActivationMethod_min( degreeOfSupport_18 , membership );      
                        defuzzify_Indice_Popularidade[i] += ruleAccumulationMethod_max( defuzzify_Indice_Popularidade[i], y );
                }
        }

        // RULE 19 : IF ((Quantidade_Analises_Positivas IS Media) AND (Preco IS Alto)) AND (Quantidade_Espectadores IS Baixa) THEN Indice_Popularidade IS Medio;
        double degreeOfSupport_19 = 1.0 * ( ruleConnectionMethod_and(ruleConnectionMethod_and(Quantidade_Analises_Positivas_Media , Preco_Alto) , Quantidade_Espectadores_Baixa) );
        if( degreeOfSupport_19 > 0 ) {
                for (int i = 0 ; i < 1000 ; i++ ) {
                        double x = 0.0 + i * 0.1;
                        double membership = membership_Indice_Popularidade_Medio(x);
                        double y = ruleActivationMethod_min( degreeOfSupport_19 , membership );      
                        defuzzify_Indice_Popularidade[i] += ruleAccumulationMethod_max( defuzzify_Indice_Popularidade[i], y );
                }
        }

        // RULE 20 : IF ((Quantidade_Analises_Positivas IS Media) AND (Preco IS MuitoAlto)) AND (Quantidade_Espectadores IS Baixa) THEN Indice_Popularidade IS Baixo;
        double degreeOfSupport_20 = 1.0 * ( ruleConnectionMethod_and(ruleConnectionMethod_and(Quantidade_Analises_Positivas_Media , Preco_MuitoAlto) , Quantidade_Espectadores_Baixa) );
        if( degreeOfSupport_20 > 0 ) {
                for (int i = 0 ; i < 1000 ; i++ ) {
                        double x = 0.0 + i * 0.1;
                        double membership = membership_Indice_Popularidade_Baixo(x);
                        double y = ruleActivationMethod_min( degreeOfSupport_20 , membership );      
                        defuzzify_Indice_Popularidade[i] += ruleAccumulationMethod_max( defuzzify_Indice_Popularidade[i], y );
                }
        }

        // RULE 21 : IF ((Quantidade_Analises_Positivas IS Media) AND (Preco IS MuitoBaixo)) AND (Quantidade_Espectadores IS Media) THEN Indice_Popularidade IS Medio;
        double degreeOfSupport_21 = 1.0 * ( ruleConnectionMethod_and(ruleConnectionMethod_and(Quantidade_Analises_Positivas_Media , Preco_MuitoBaixo) , Quantidade_Espectadores_Media) );
        if( degreeOfSupport_21 > 0 ) {
                for (int i = 0 ; i < 1000 ; i++ ) {
                        double x = 0.0 + i * 0.1;
                        double membership = membership_Indice_Popularidade_Medio(x);
                        double y = ruleActivationMethod_min( degreeOfSupport_21 , membership );      
                        defuzzify_Indice_Popularidade[i] += ruleAccumulationMethod_max( defuzzify_Indice_Popularidade[i], y );
                }
        }

        // RULE 22 : IF ((Quantidade_Analises_Positivas IS Media) AND (Preco IS Baixo)) AND (Quantidade_Espectadores IS Media) THEN Indice_Popularidade IS Medio;
        double degreeOfSupport_22 = 1.0 * ( ruleConnectionMethod_and(ruleConnectionMethod_and(Quantidade_Analises_Positivas_Media , Preco_Baixo) , Quantidade_Espectadores_Media) );
        if( degreeOfSupport_22 > 0 ) {
                for (int i = 0 ; i < 1000 ; i++ ) {
                        double x = 0.0 + i * 0.1;
                        double membership = membership_Indice_Popularidade_Medio(x);
                        double y = ruleActivationMethod_min( degreeOfSupport_22 , membership );      
                        defuzzify_Indice_Popularidade[i] += ruleAccumulationMethod_max( defuzzify_Indice_Popularidade[i], y );
                }
        }

        // RULE 23 : IF ((Quantidade_Analises_Positivas IS Media) AND (Preco IS Medio)) AND (Quantidade_Espectadores IS Media) THEN Indice_Popularidade IS Alto;
        double degreeOfSupport_23 = 1.0 * ( ruleConnectionMethod_and(ruleConnectionMethod_and(Quantidade_Analises_Positivas_Media , Preco_Medio) , Quantidade_Espectadores_Media) );
        if( degreeOfSupport_23 > 0 ) {
                for (int i = 0 ; i < 1000 ; i++ ) {
                        double x = 0.0 + i * 0.1;
                        double membership = membership_Indice_Popularidade_Alto(x);
                        double y = ruleActivationMethod_min( degreeOfSupport_23 , membership );      
                        defuzzify_Indice_Popularidade[i] += ruleAccumulationMethod_max( defuzzify_Indice_Popularidade[i], y );
                }
        }

        // RULE 24 : IF ((Quantidade_Analises_Positivas IS Media) AND (Preco IS Alto)) AND (Quantidade_Espectadores IS Media) THEN Indice_Popularidade IS Medio;
        double degreeOfSupport_24 = 1.0 * ( ruleConnectionMethod_and(ruleConnectionMethod_and(Quantidade_Analises_Positivas_Media , Preco_Alto) , Quantidade_Espectadores_Media) );
        if( degreeOfSupport_24 > 0 ) {
                for (int i = 0 ; i < 1000 ; i++ ) {
                        double x = 0.0 + i * 0.1;
                        double membership = membership_Indice_Popularidade_Medio(x);
                        double y = ruleActivationMethod_min( degreeOfSupport_24 , membership );      
                        defuzzify_Indice_Popularidade[i] += ruleAccumulationMethod_max( defuzzify_Indice_Popularidade[i], y );
                }
        }

        // RULE 25 : IF ((Quantidade_Analises_Positivas IS Media) AND (Preco IS MuitoAlto)) AND (Quantidade_Espectadores IS Media) THEN Indice_Popularidade IS Medio;
        double degreeOfSupport_25 = 1.0 * ( ruleConnectionMethod_and(ruleConnectionMethod_and(Quantidade_Analises_Positivas_Media , Preco_MuitoAlto) , Quantidade_Espectadores_Media) );
        if( degreeOfSupport_25 > 0 ) {
                for (int i = 0 ; i < 1000 ; i++ ) {
                        double x = 0.0 + i * 0.1;
                        double membership = membership_Indice_Popularidade_Medio(x);
                        double y = ruleActivationMethod_min( degreeOfSupport_25 , membership );      
                        defuzzify_Indice_Popularidade[i] += ruleAccumulationMethod_max( defuzzify_Indice_Popularidade[i], y );
                }
        }

        // RULE 26 : IF ((Quantidade_Analises_Positivas IS Media) AND (Preco IS MuitoBaixo)) AND (Quantidade_Espectadores IS Alta) THEN Indice_Popularidade IS Medio;
        double degreeOfSupport_26 = 1.0 * ( ruleConnectionMethod_and(ruleConnectionMethod_and(Quantidade_Analises_Positivas_Media , Preco_MuitoBaixo) , Quantidade_Espectadores_Alta) );
        if( degreeOfSupport_26 > 0 ) {
                for (int i = 0 ; i < 1000 ; i++ ) {
                        double x = 0.0 + i * 0.1;
                        double membership = membership_Indice_Popularidade_Medio(x);
                        double y = ruleActivationMethod_min( degreeOfSupport_26 , membership );      
                        defuzzify_Indice_Popularidade[i] += ruleAccumulationMethod_max( defuzzify_Indice_Popularidade[i], y );
                }
        }

        // RULE 27 : IF ((Quantidade_Analises_Positivas IS Media) AND (Preco IS Baixo)) AND (Quantidade_Espectadores IS Alta) THEN Indice_Popularidade IS Medio;
        double degreeOfSupport_27 = 1.0 * ( ruleConnectionMethod_and(ruleConnectionMethod_and(Quantidade_Analises_Positivas_Media , Preco_Baixo) , Quantidade_Espectadores_Alta) );
        if( degreeOfSupport_27 > 0 ) {
                for (int i = 0 ; i < 1000 ; i++ ) {
                        double x = 0.0 + i * 0.1;
                        double membership = membership_Indice_Popularidade_Medio(x);
                        double y = ruleActivationMethod_min( degreeOfSupport_27 , membership );      
                        defuzzify_Indice_Popularidade[i] += ruleAccumulationMethod_max( defuzzify_Indice_Popularidade[i], y );
                }
        }

        // RULE 28 : IF ((Quantidade_Analises_Positivas IS Media) AND (Preco IS Medio)) AND (Quantidade_Espectadores IS Alta) THEN Indice_Popularidade IS Alto;
        double degreeOfSupport_28 = 1.0 * ( ruleConnectionMethod_and(ruleConnectionMethod_and(Quantidade_Analises_Positivas_Media , Preco_Medio) , Quantidade_Espectadores_Alta) );
        if( degreeOfSupport_28 > 0 ) {
                for (int i = 0 ; i < 1000 ; i++ ) {
                        double x = 0.0 + i * 0.1;
                        double membership = membership_Indice_Popularidade_Alto(x);
                        double y = ruleActivationMethod_min( degreeOfSupport_28 , membership );      
                        defuzzify_Indice_Popularidade[i] += ruleAccumulationMethod_max( defuzzify_Indice_Popularidade[i], y );
                }
        }

        // RULE 29 : IF ((Quantidade_Analises_Positivas IS Media) AND (Preco IS Alto)) AND (Quantidade_Espectadores IS Alta) THEN Indice_Popularidade IS Medio;
        double degreeOfSupport_29 = 1.0 * ( ruleConnectionMethod_and(ruleConnectionMethod_and(Quantidade_Analises_Positivas_Media , Preco_Alto) , Quantidade_Espectadores_Alta) );
        if( degreeOfSupport_29 > 0 ) {
                for (int i = 0 ; i < 1000 ; i++ ) {
                        double x = 0.0 + i * 0.1;
                        double membership = membership_Indice_Popularidade_Medio(x);
                        double y = ruleActivationMethod_min( degreeOfSupport_29 , membership );      
                        defuzzify_Indice_Popularidade[i] += ruleAccumulationMethod_max( defuzzify_Indice_Popularidade[i], y );
                }
        }

        // RULE 30 : IF ((Quantidade_Analises_Positivas IS Media) AND (Preco IS MuitoAlto)) AND (Quantidade_Espectadores IS Alta) THEN Indice_Popularidade IS Medio;
        double degreeOfSupport_30 = 1.0 * ( ruleConnectionMethod_and(ruleConnectionMethod_and(Quantidade_Analises_Positivas_Media , Preco_MuitoAlto) , Quantidade_Espectadores_Alta) );
        if( degreeOfSupport_30 > 0 ) {
                for (int i = 0 ; i < 1000 ; i++ ) {
                        double x = 0.0 + i * 0.1;
                        double membership = membership_Indice_Popularidade_Medio(x);
                        double y = ruleActivationMethod_min( degreeOfSupport_30 , membership );      
                        defuzzify_Indice_Popularidade[i] += ruleAccumulationMethod_max( defuzzify_Indice_Popularidade[i], y );
                }
        }

        // RULE 31 : IF ((Quantidade_Analises_Positivas IS Alta) AND (Preco IS MuitoBaixo)) AND (Quantidade_Espectadores IS Baixa) THEN Indice_Popularidade IS Baixo;
        double degreeOfSupport_31 = 1.0 * ( ruleConnectionMethod_and(ruleConnectionMethod_and(Quantidade_Analises_Positivas_Alta , Preco_MuitoBaixo) , Quantidade_Espectadores_Baixa) );
        if( degreeOfSupport_31 > 0 ) {
                for (int i = 0 ; i < 1000 ; i++ ) {
                        double x = 0.0 + i * 0.1;
                        double membership = membership_Indice_Popularidade_Baixo(x);
                        double y = ruleActivationMethod_min( degreeOfSupport_31 , membership );      
                        defuzzify_Indice_Popularidade[i] += ruleAccumulationMethod_max( defuzzify_Indice_Popularidade[i], y );
                }
        }

        // RULE 32 : IF ((Quantidade_Analises_Positivas IS Alta) AND (Preco IS Baixo)) AND (Quantidade_Espectadores IS Baixa) THEN Indice_Popularidade IS Medio;
        double degreeOfSupport_32 = 1.0 * ( ruleConnectionMethod_and(ruleConnectionMethod_and(Quantidade_Analises_Positivas_Alta , Preco_Baixo) , Quantidade_Espectadores_Baixa) );
        if( degreeOfSupport_32 > 0 ) {
                for (int i = 0 ; i < 1000 ; i++ ) {
                        double x = 0.0 + i * 0.1;
                        double membership = membership_Indice_Popularidade_Medio(x);
                        double y = ruleActivationMethod_min( degreeOfSupport_32 , membership );      
                        defuzzify_Indice_Popularidade[i] += ruleAccumulationMethod_max( defuzzify_Indice_Popularidade[i], y );
                }
        }

        // RULE 33 : IF ((Quantidade_Analises_Positivas IS Alta) AND (Preco IS Medio)) AND (Quantidade_Espectadores IS Baixa) THEN Indice_Popularidade IS Medio;
        double degreeOfSupport_33 = 1.0 * ( ruleConnectionMethod_and(ruleConnectionMethod_and(Quantidade_Analises_Positivas_Alta , Preco_Medio) , Quantidade_Espectadores_Baixa) );
        if( degreeOfSupport_33 > 0 ) {
                for (int i = 0 ; i < 1000 ; i++ ) {
                        double x = 0.0 + i * 0.1;
                        double membership = membership_Indice_Popularidade_Medio(x);
                        double y = ruleActivationMethod_min( degreeOfSupport_33 , membership );      
                        defuzzify_Indice_Popularidade[i] += ruleAccumulationMethod_max( defuzzify_Indice_Popularidade[i], y );
                }
        }

        // RULE 34 : IF ((Quantidade_Analises_Positivas IS Alta) AND (Preco IS Alto)) AND (Quantidade_Espectadores IS Baixa) THEN Indice_Popularidade IS Medio;
        double degreeOfSupport_34 = 1.0 * ( ruleConnectionMethod_and(ruleConnectionMethod_and(Quantidade_Analises_Positivas_Alta , Preco_Alto) , Quantidade_Espectadores_Baixa) );
        if( degreeOfSupport_34 > 0 ) {
                for (int i = 0 ; i < 1000 ; i++ ) {
                        double x = 0.0 + i * 0.1;
                        double membership = membership_Indice_Popularidade_Medio(x);
                        double y = ruleActivationMethod_min( degreeOfSupport_34 , membership );      
                        defuzzify_Indice_Popularidade[i] += ruleAccumulationMethod_max( defuzzify_Indice_Popularidade[i], y );
                }
        }

        // RULE 35 : IF ((Quantidade_Analises_Positivas IS Alta) AND (Preco IS MuitoAlto)) AND (Quantidade_Espectadores IS Baixa) THEN Indice_Popularidade IS Baixo;
        double degreeOfSupport_35 = 1.0 * ( ruleConnectionMethod_and(ruleConnectionMethod_and(Quantidade_Analises_Positivas_Alta , Preco_MuitoAlto) , Quantidade_Espectadores_Baixa) );
        if( degreeOfSupport_35 > 0 ) {
                for (int i = 0 ; i < 1000 ; i++ ) {
                        double x = 0.0 + i * 0.1;
                        double membership = membership_Indice_Popularidade_Baixo(x);
                        double y = ruleActivationMethod_min( degreeOfSupport_35 , membership );      
                        defuzzify_Indice_Popularidade[i] += ruleAccumulationMethod_max( defuzzify_Indice_Popularidade[i], y );
                }
        }

        // RULE 36 : IF ((Quantidade_Analises_Positivas IS Alta) AND (Preco IS MuitoBaixo)) AND (Quantidade_Espectadores IS Media) THEN Indice_Popularidade IS Medio;
        double degreeOfSupport_36 = 1.0 * ( ruleConnectionMethod_and(ruleConnectionMethod_and(Quantidade_Analises_Positivas_Alta , Preco_MuitoBaixo) , Quantidade_Espectadores_Media) );
        if( degreeOfSupport_36 > 0 ) {
                for (int i = 0 ; i < 1000 ; i++ ) {
                        double x = 0.0 + i * 0.1;
                        double membership = membership_Indice_Popularidade_Medio(x);
                        double y = ruleActivationMethod_min( degreeOfSupport_36 , membership );      
                        defuzzify_Indice_Popularidade[i] += ruleAccumulationMethod_max( defuzzify_Indice_Popularidade[i], y );
                }
        }

        // RULE 37 : IF ((Quantidade_Analises_Positivas IS Alta) AND (Preco IS Baixo)) AND (Quantidade_Espectadores IS Media) THEN Indice_Popularidade IS Medio;
        double degreeOfSupport_37 = 1.0 * ( ruleConnectionMethod_and(ruleConnectionMethod_and(Quantidade_Analises_Positivas_Alta , Preco_Baixo) , Quantidade_Espectadores_Media) );
        if( degreeOfSupport_37 > 0 ) {
                for (int i = 0 ; i < 1000 ; i++ ) {
                        double x = 0.0 + i * 0.1;
                        double membership = membership_Indice_Popularidade_Medio(x);
                        double y = ruleActivationMethod_min( degreeOfSupport_37 , membership );      
                        defuzzify_Indice_Popularidade[i] += ruleAccumulationMethod_max( defuzzify_Indice_Popularidade[i], y );
                }
        }

        // RULE 38 : IF ((Quantidade_Analises_Positivas IS Alta) AND (Preco IS Medio)) AND (Quantidade_Espectadores IS Media) THEN Indice_Popularidade IS Alto;
        double degreeOfSupport_38 = 1.0 * ( ruleConnectionMethod_and(ruleConnectionMethod_and(Quantidade_Analises_Positivas_Alta , Preco_Medio) , Quantidade_Espectadores_Media) );
        if( degreeOfSupport_38 > 0 ) {
                for (int i = 0 ; i < 1000 ; i++ ) {
                        double x = 0.0 + i * 0.1;
                        double membership = membership_Indice_Popularidade_Alto(x);
                        double y = ruleActivationMethod_min( degreeOfSupport_38 , membership );      
                        defuzzify_Indice_Popularidade[i] += ruleAccumulationMethod_max( defuzzify_Indice_Popularidade[i], y );
                }
        }

        // RULE 39 : IF ((Quantidade_Analises_Positivas IS Alta) AND (Preco IS Alto)) AND (Quantidade_Espectadores IS Media) THEN Indice_Popularidade IS Medio;
        double degreeOfSupport_39 = 1.0 * ( ruleConnectionMethod_and(ruleConnectionMethod_and(Quantidade_Analises_Positivas_Alta , Preco_Alto) , Quantidade_Espectadores_Media) );
        if( degreeOfSupport_39 > 0 ) {
                for (int i = 0 ; i < 1000 ; i++ ) {
                        double x = 0.0 + i * 0.1;
                        double membership = membership_Indice_Popularidade_Medio(x);
                        double y = ruleActivationMethod_min( degreeOfSupport_39 , membership );      
                        defuzzify_Indice_Popularidade[i] += ruleAccumulationMethod_max( defuzzify_Indice_Popularidade[i], y );
                }
        }

        // RULE 40 : IF ((Quantidade_Analises_Positivas IS Alta) AND (Preco IS MuitoAlto)) AND (Quantidade_Espectadores IS Media) THEN Indice_Popularidade IS Medio;
        double degreeOfSupport_40 = 1.0 * ( ruleConnectionMethod_and(ruleConnectionMethod_and(Quantidade_Analises_Positivas_Alta , Preco_MuitoAlto) , Quantidade_Espectadores_Media) );
        if( degreeOfSupport_40 > 0 ) {
                for (int i = 0 ; i < 1000 ; i++ ) {
                        double x = 0.0 + i * 0.1;
                        double membership = membership_Indice_Popularidade_Medio(x);
                        double y = ruleActivationMethod_min( degreeOfSupport_40 , membership );      
                        defuzzify_Indice_Popularidade[i] += ruleAccumulationMethod_max( defuzzify_Indice_Popularidade[i], y );
                }
        }

        // RULE 41 : IF ((Quantidade_Analises_Positivas IS Alta) AND (Preco IS MuitoBaixo)) AND (Quantidade_Espectadores IS Alta) THEN Indice_Popularidade IS Medio;
        double degreeOfSupport_41 = 1.0 * ( ruleConnectionMethod_and(ruleConnectionMethod_and(Quantidade_Analises_Positivas_Alta , Preco_MuitoBaixo) , Quantidade_Espectadores_Alta) );
        if( degreeOfSupport_41 > 0 ) {
                for (int i = 0 ; i < 1000 ; i++ ) {
                        double x = 0.0 + i * 0.1;
                        double membership = membership_Indice_Popularidade_Medio(x);
                        double y = ruleActivationMethod_min( degreeOfSupport_41 , membership );      
                        defuzzify_Indice_Popularidade[i] += ruleAccumulationMethod_max( defuzzify_Indice_Popularidade[i], y );
                }
        }

        // RULE 42 : IF ((Quantidade_Analises_Positivas IS Alta) AND (Preco IS Baixo)) AND (Quantidade_Espectadores IS Alta) THEN Indice_Popularidade IS Alto;
        double degreeOfSupport_42 = 1.0 * ( ruleConnectionMethod_and(ruleConnectionMethod_and(Quantidade_Analises_Positivas_Alta , Preco_Baixo) , Quantidade_Espectadores_Alta) );
        if( degreeOfSupport_42 > 0 ) {
                for (int i = 0 ; i < 1000 ; i++ ) {
                        double x = 0.0 + i * 0.1;
                        double membership = membership_Indice_Popularidade_Alto(x);
                        double y = ruleActivationMethod_min( degreeOfSupport_42 , membership );      
                        defuzzify_Indice_Popularidade[i] += ruleAccumulationMethod_max( defuzzify_Indice_Popularidade[i], y );
                }
        }

        // RULE 43 : IF ((Quantidade_Analises_Positivas IS Alta) AND (Preco IS Medio)) AND (Quantidade_Espectadores IS Alta) THEN Indice_Popularidade IS Alto;
        double degreeOfSupport_43 = 1.0 * ( ruleConnectionMethod_and(ruleConnectionMethod_and(Quantidade_Analises_Positivas_Alta , Preco_Medio) , Quantidade_Espectadores_Alta) );
        if( degreeOfSupport_43 > 0 ) {
                for (int i = 0 ; i < 1000 ; i++ ) {
                        double x = 0.0 + i * 0.1;
                        double membership = membership_Indice_Popularidade_Alto(x);
                        double y = ruleActivationMethod_min( degreeOfSupport_43 , membership );      
                        defuzzify_Indice_Popularidade[i] += ruleAccumulationMethod_max( defuzzify_Indice_Popularidade[i], y );
                }
        }

        // RULE 44 : IF ((Quantidade_Analises_Positivas IS Alta) AND (Preco IS Alto)) AND (Quantidade_Espectadores IS Alta) THEN Indice_Popularidade IS Alto;
        double degreeOfSupport_44 = 1.0 * ( ruleConnectionMethod_and(ruleConnectionMethod_and(Quantidade_Analises_Positivas_Alta , Preco_Alto) , Quantidade_Espectadores_Alta) );
        if( degreeOfSupport_44 > 0 ) {
                for (int i = 0 ; i < 1000 ; i++ ) {
                        double x = 0.0 + i * 0.1;
                        double membership = membership_Indice_Popularidade_Alto(x);
                        double y = ruleActivationMethod_min( degreeOfSupport_44 , membership );      
                        defuzzify_Indice_Popularidade[i] += ruleAccumulationMethod_max( defuzzify_Indice_Popularidade[i], y );
                }
        }

        // RULE 45 : IF ((Quantidade_Analises_Positivas IS Alta) AND (Preco IS MuitoAlto)) AND (Quantidade_Espectadores IS Alta) THEN Indice_Popularidade IS Medio;
        double degreeOfSupport_45 = 1.0 * ( ruleConnectionMethod_and(ruleConnectionMethod_and(Quantidade_Analises_Positivas_Alta , Preco_MuitoAlto) , Quantidade_Espectadores_Alta) );
        if( degreeOfSupport_45 > 0 ) {
                for (int i = 0 ; i < 1000 ; i++ ) {
                        double x = 0.0 + i * 0.1;
                        double membership = membership_Indice_Popularidade_Medio(x);
                        double y = ruleActivationMethod_min( degreeOfSupport_45 , membership );      
                        defuzzify_Indice_Popularidade[i] += ruleAccumulationMethod_max( defuzzify_Indice_Popularidade[i], y );
                }
        }

}

// Defuzzify
void FunctionBlock_game::defuzzify() {
        double sum_Indice_Popularidade = 0.0;
        double wsum_Indice_Popularidade = 0.0;
        for (int i = 0; i < 1000 ; i++ ) {
                double x = 0.0 + i * 0.1;
                sum_Indice_Popularidade += defuzzify_Indice_Popularidade[i];
                wsum_Indice_Popularidade += x * defuzzify_Indice_Popularidade[i];
        }
        Indice_Popularidade = wsum_Indice_Popularidade / sum_Indice_Popularidade;
}

// Fuzzify all variables
void FunctionBlock_game::fuzzify() {
        Preco_Alto = membership_Preco_Alto(Preco);
        Preco_Baixo = membership_Preco_Baixo(Preco);
        Preco_Medio = membership_Preco_Medio(Preco);
        Preco_MuitoAlto = membership_Preco_MuitoAlto(Preco);
        Preco_MuitoBaixo = membership_Preco_MuitoBaixo(Preco);
        Quantidade_Analises_Positivas_Alta = membership_Quantidade_Analises_Positivas_Alta(Quantidade_Analises_Positivas);
        Quantidade_Analises_Positivas_Baixa = membership_Quantidade_Analises_Positivas_Baixa(Quantidade_Analises_Positivas);
        Quantidade_Analises_Positivas_Media = membership_Quantidade_Analises_Positivas_Media(Quantidade_Analises_Positivas);
        Quantidade_Espectadores_Alta = membership_Quantidade_Espectadores_Alta(Quantidade_Espectadores);
        Quantidade_Espectadores_Baixa = membership_Quantidade_Espectadores_Baixa(Quantidade_Espectadores);
        Quantidade_Espectadores_Media = membership_Quantidade_Espectadores_Media(Quantidade_Espectadores);
}

// Membership functions
double FunctionBlock_game::membership_Indice_Popularidade_Alto(double x) {
        if ( x <= 50.0 )        return 0.0;
        if ( x > 100.0 )        return 1.0;
        if ( x <= 75.0 )        return 0.0 + ( 1.0 - 0.0 ) * ( ( x - 50.0 ) / ( 75.0 - 50.0 ) );     
        if ( x <= 100.0 )       return 1.0 + ( 1.0 - 1.0 ) * ( ( x - 75.0 ) / ( 100.0 - 75.0 ) );    
}

double FunctionBlock_game::membership_Indice_Popularidade_Baixo(double x) {
        if ( x <= 0.0 ) return 1.0;
        if ( x > 50.0 ) return 0.0;
        if ( x <= 25.0 )        return 1.0 + ( 1.0 - 1.0 ) * ( ( x - 0.0 ) / ( 25.0 - 0.0 ) );       
        if ( x <= 50.0 )        return 1.0 + ( 0.0 - 1.0 ) * ( ( x - 25.0 ) / ( 50.0 - 25.0 ) );     
}

double FunctionBlock_game::membership_Indice_Popularidade_Medio(double x) {
        if ( x <= 25.0 )        return 0.0;
        if ( x > 75.0 ) return 0.0;
        if ( x <= 50.0 )        return 0.0 + ( 1.0 - 0.0 ) * ( ( x - 25.0 ) / ( 50.0 - 25.0 ) );     
        if ( x <= 75.0 )        return 1.0 + ( 0.0 - 1.0 ) * ( ( x - 50.0 ) / ( 75.0 - 50.0 ) );     
}

double FunctionBlock_game::membership_Preco_Alto(double x) {
        if ( x <= 75.0 )        return 0.0;
        if ( x > 160.0 )        return 0.0;
        if ( x <= 90.0 )        return 0.0 + ( 1.0 - 0.0 ) * ( ( x - 75.0 ) / ( 90.0 - 75.0 ) );     
        if ( x <= 150.0 )       return 1.0 + ( 1.0 - 1.0 ) * ( ( x - 90.0 ) / ( 150.0 - 90.0 ) );    
        if ( x <= 160.0 )       return 1.0 + ( 0.0 - 1.0 ) * ( ( x - 150.0 ) / ( 160.0 - 150.0 ) );  
}

double FunctionBlock_game::membership_Preco_Baixo(double x) {
        if ( x <= 5.0 ) return 0.0;
        if ( x > 25.0 ) return 0.0;
        if ( x <= 10.0 )        return 0.0 + ( 1.0 - 0.0 ) * ( ( x - 5.0 ) / ( 10.0 - 5.0 ) );       
        if ( x <= 20.0 )        return 1.0 + ( 1.0 - 1.0 ) * ( ( x - 10.0 ) / ( 20.0 - 10.0 ) );     
        if ( x <= 25.0 )        return 1.0 + ( 0.0 - 1.0 ) * ( ( x - 20.0 ) / ( 25.0 - 20.0 ) );     
}

double FunctionBlock_game::membership_Preco_Medio(double x) {
        if ( x <= 20.0 )        return 0.0;
        if ( x > 90.0 ) return 0.0;
        if ( x <= 25.0 )        return 0.0 + ( 1.0 - 0.0 ) * ( ( x - 20.0 ) / ( 25.0 - 20.0 ) );     
        if ( x <= 75.0 )        return 1.0 + ( 1.0 - 1.0 ) * ( ( x - 25.0 ) / ( 75.0 - 25.0 ) );     
        if ( x <= 90.0 )        return 1.0 + ( 0.0 - 1.0 ) * ( ( x - 75.0 ) / ( 90.0 - 75.0 ) );     
}

double FunctionBlock_game::membership_Preco_MuitoAlto(double x) {
        if ( x <= 150.0 )       return 0.0;
        if ( x > 250.0 )        return 1.0;
        if ( x <= 160.0 )       return 0.0 + ( 1.0 - 0.0 ) * ( ( x - 150.0 ) / ( 160.0 - 150.0 ) );  
        if ( x <= 250.0 )       return 1.0 + ( 1.0 - 1.0 ) * ( ( x - 160.0 ) / ( 250.0 - 160.0 ) );  
}

double FunctionBlock_game::membership_Preco_MuitoBaixo(double x) {
        if ( x <= 0.0 ) return 1.0;
        if ( x > 10.0 ) return 0.0;
        if ( x <= 5.0 ) return 1.0 + ( 1.0 - 1.0 ) * ( ( x - 0.0 ) / ( 5.0 - 0.0 ) );
        if ( x <= 10.0 )        return 1.0 + ( 0.0 - 1.0 ) * ( ( x - 5.0 ) / ( 10.0 - 5.0 ) );       
}

double FunctionBlock_game::membership_Quantidade_Analises_Positivas_Alta(double x) {
        if ( x <= 900.0 )       return 0.0;
        if ( x > 1500.0 )       return 1.0;
        if ( x <= 1000.0 )      return 0.0 + ( 1.0 - 0.0 ) * ( ( x - 900.0 ) / ( 1000.0 - 900.0 ) ); 
        if ( x <= 1500.0 )      return 1.0 + ( 1.0 - 1.0 ) * ( ( x - 1000.0 ) / ( 1500.0 - 1000.0 ) );
}

double FunctionBlock_game::membership_Quantidade_Analises_Positivas_Baixa(double x) {
        if ( x <= 0.0 ) return 1.0;
        if ( x > 500.0 )        return 0.0;
        if ( x <= 400.0 )       return 1.0 + ( 1.0 - 1.0 ) * ( ( x - 0.0 ) / ( 400.0 - 0.0 ) );      
        if ( x <= 500.0 )       return 1.0 + ( 0.0 - 1.0 ) * ( ( x - 400.0 ) / ( 500.0 - 400.0 ) );  
}

double FunctionBlock_game::membership_Quantidade_Analises_Positivas_Media(double x) {
        if ( x <= 400.0 )       return 0.0;
        if ( x > 1000.0 )       return 0.0;
        if ( x <= 500.0 )       return 0.0 + ( 1.0 - 0.0 ) * ( ( x - 400.0 ) / ( 500.0 - 400.0 ) );  
        if ( x <= 900.0 )       return 1.0 + ( 1.0 - 1.0 ) * ( ( x - 500.0 ) / ( 900.0 - 500.0 ) );  
        if ( x <= 1000.0 )      return 1.0 + ( 0.0 - 1.0 ) * ( ( x - 900.0 ) / ( 1000.0 - 900.0 ) ); 
}

double FunctionBlock_game::membership_Quantidade_Espectadores_Alta(double x) {
        if ( x <= 3000.0 )      return 0.0;
        if ( x > 5000.0 )       return 1.0;
        if ( x <= 3500.0 )      return 0.0 + ( 1.0 - 0.0 ) * ( ( x - 3000.0 ) / ( 3500.0 - 3000.0 ) );
        if ( x <= 5000.0 )      return 1.0 + ( 1.0 - 1.0 ) * ( ( x - 3500.0 ) / ( 5000.0 - 3500.0 ) );
}

double FunctionBlock_game::membership_Quantidade_Espectadores_Baixa(double x) {
        if ( x <= 0.0 ) return 1.0;
        if ( x > 1000.0 )       return 0.0;
        if ( x <= 800.0 )       return 1.0 + ( 1.0 - 1.0 ) * ( ( x - 0.0 ) / ( 800.0 - 0.0 ) );      
        if ( x <= 1000.0 )      return 1.0 + ( 0.0 - 1.0 ) * ( ( x - 800.0 ) / ( 1000.0 - 800.0 ) ); 
}

double FunctionBlock_game::membership_Quantidade_Espectadores_Media(double x) {
        if ( x <= 800.0 )       return 0.0;
        if ( x > 3500.0 )       return 0.0;
        if ( x <= 1000.0 )      return 0.0 + ( 1.0 - 0.0 ) * ( ( x - 800.0 ) / ( 1000.0 - 800.0 ) ); 
        if ( x <= 3000.0 )      return 1.0 + ( 1.0 - 1.0 ) * ( ( x - 1000.0 ) / ( 3000.0 - 1000.0 ) );
        if ( x <= 3500.0 )      return 1.0 + ( 0.0 - 1.0 ) * ( ( x - 3000.0 ) / ( 3500.0 - 3000.0 ) );
}


// Print
void FunctionBlock_game::print() {

        cout << "Preco:\t\t\t\t\tR$ " << Preco << " ";
        cout << ((Preco_MuitoBaixo) ? "(Muito Baixo)" : "");
        cout << ((Preco_Baixo) ? "(Baixo)" : "");
        cout << ((Preco_Medio) ? "(Medio)" : "");
        cout << ((Preco_Alto) ? "(Alto)" : "");
        cout << ((Preco_MuitoAlto) ? "(Muito Alto)" : "");
        cout << endl;

        cout << "Quantidade de analises positivas:\t" << Quantidade_Analises_Positivas << " ";
        cout << ((Quantidade_Analises_Positivas_Baixa) ? "(Baixa)" : "");
        cout << ((Quantidade_Analises_Positivas_Media) ? "(Media)" : "");
        cout << ((Quantidade_Analises_Positivas_Alta) ? "(Alta)" : "");
        cout << endl;

        cout << "Quantidade de espectadores diarios:\t" << Quantidade_Espectadores << " ";
        cout << ((Quantidade_Espectadores_Baixa) ? "(Baixa)" : "");
        cout << ((Quantidade_Espectadores_Media) ? "(Media)" : "");
        cout << ((Quantidade_Espectadores_Alta) ? "(Alta)" : "");
        cout << endl << endl;

        cout << "Indice de Popularidade: \t\t" << Indice_Popularidade << "%" << endl << endl;
}

// Reset output
void FunctionBlock_game::reset() {
        for( int i=0 ; i < 1000 ; i++ ) { defuzzify_Indice_Popularidade[i] = 0.0; }
}

#endif