# -*- coding: utf-8 -*-
"""ANÁLISE DO IMPACTO DE DIFERENTES FATORES NOS SINTOMAS DE DOENÇAS CRÔNICAS AUTOIMUNES.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gsRWdCG_iYz7P5U3wCToum5I-ayOrilc

# **ANÁLISE DO IMPACTO DE DIFERENTES TRATAMENTOS NOS SINTOMAS DE DOENÇAS CRÔNICAS AUTOIMUNES**

*Caio Gonzaga Bernils*

*Gustavo Henrique Stahl Müller*

*Paulo Henrique Rohling*

# **INTRODUÇÃO**
O dataset “**Chronic illness: symptoms, treatments and triggers**” reúne dados gerados por pacientes que sofrem de doenças crônicas autoimunes. Os pacientes registraram diariamente e por conta própria a atual a gravidade dos sintomas, o status do tratamento e os detalhes sobre as doses de quaisquer medicamentos que estejam tomando. 

São registrados, ainda, possíveis gatilhos ambientais que possam influenciar na melhora ou no agravamento dos sintomas da doença, como alimentos, situações estressantes ou atividades físicas incomuns. Este dataset possui **9 atributos e 7976223 registros**.

# **SETUP INICIAL**

## **Imports**
"""

import pandas as pandas
import numpy as np
import matplotlib
import matplotlib.pyplot as plot
import seaborn as sns

# Associação
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules
from mlxtend.preprocessing import TransactionEncoder

pandas.set_option('display.float_format', lambda x: '%.5f' % x)
pandas.set_option('display.max_rows', 20)

def printBar():
	print("_" * 60 + "\n")

"""## **Carregando dataset**"""

from google.colab import drive
drive.mount('/content/drive')

dataset = pandas.read_csv("/content/drive/MyDrive/Colab Notebooks/dataset.csv")
print(dataset)

"""## **Primeiros 10 registros**"""

dataset.head(10)

"""## **Quantidade de valores únicos por coluna**"""

# Nota-se aqui que temos registros de 42283 usuários diferentes
dataset.nunique()

"""# **LIMPEZA DOS DADOS**

## **User ID**

A coluna `user_id` é constituida por registros alfanuméricos que identificam um usuário. Para economizar memória, é aplicada uma transformação nestes registros para que se tornem um simples `integer`.
"""

# pandas.Categorical agrupa em um objeto os valores únicos de um conjunto, atribuindo um código em pandas.Categorical.codes
ids = pandas.Categorical(dataset['user_id'])

# Atribuindo os códigos gerados (integers) para a coluna `user_id`
dataset["user_id"] = ids.codes

dataset.head(10)

"""## **Idade**

Como pode ser visto abaixo, a coluna `age` possui valores inválidos, como números negativos e números que vão além do tempo de vida normal de um ser humano. Para evitar que estes *outliers* afetem a análise, os zeros serão trocados por `NaN`.
"""

dataset.age.describe()

dataset[(dataset['age'] > 100)].sort_values(by='age',ascending=True).head(10)

dataset[(dataset['age'] <= 0)].sort_values(by='age',ascending=True).head()

"""
Como os valores acima de 100 anos começam em 118, transformou-se todas as idades superiores
a 117 em `NaN`, bem como as idades menores ou iguais a zero.
"""
dataset = dataset.assign(age = lambda x: x.age.where(x.age.gt(0)))
dataset = dataset.assign(age = lambda x: x.age.where(x.age.le(117)))

dataset[dataset['age'] > 100].sort_values(by='age',ascending=True).head(10)

dataset[(dataset['age'] <= 0)].sort_values(by='age',ascending=True).head()

dataset.age.describe()

"""# **ANÁLISE EXPLORATÓRIA**

## **Categorização por sexo**
"""

# Somente realizar uma contagem da ocorrência dos valores desta coluna não é o
# bastante, uma vez que o mesmo usuário provavelmente fez mais de um registro.
# É necessário agrupar os valores por `user_id`.
dataset.sex.value_counts()

# Realizando a contagem de valores por usuário
dataset_sex_unique = pandas.DataFrame([
    {'users': dataset[dataset.sex=="doesnt_say"].user_id.nunique()},
    {'users': dataset[dataset.sex=="other"].user_id.nunique()},
    {'users': dataset[dataset.sex=="male"].user_id.nunique()},
    {'users': dataset[dataset.sex=="female"].user_id.nunique()}                          
], index=['doesnt_say', 'other', 'male','female'])
dataset_sex_unique.head()

# Impressão de um gráfico para visualizar a representatividade de sexo do dataset.
# É evidente que mais de 3/4 dos registros foram feitos por mulheres.
dataset_sex_unique.users.plot(kind='pie')

"""## **Categorização por tipo de registro**"""

dataset.trackable_type.value_counts()

# Impressão de um gráfico para visualizar a representatividade de tipos de registro do dataset.
# Nota-se que existem mais registros de sintomas neste dataset.
dataset.trackable_type.value_counts().plot(kind='pie')

"""## **Categorização por país**"""

# Somente realizar uma contagem da ocorrência dos valores desta coluna não é o
# bastante, uma vez que o mesmo usuário provavelmente fez mais de um registro.
# É necessário agrupar os valores por `user_id`.
dataset.country.value_counts()

unique_countries = dataset.country.unique()
data = []

# Fazendo um dicionário de países e seu número de residentes
for country in unique_countries:
  data.append({'users': dataset[dataset.country==country].user_id.nunique()})

dataset_country_unique = pandas.DataFrame(data, index=unique_countries)

# Impressão de um gráfico para visualizar a representatividade de países do dataset.
# Nota-se que existem mais registros de pessoas que moram nos Estados Unidos.
plot.figure(figsize=(9,6))
countries = dataset_country_unique.sort_values(by=['users'], ascending=False)['users'].iloc[0:7]
sns.barplot(countries.values, countries.index)
for i, v in enumerate(countries.values):
    plot.text(0.8, i, v, color='k',fontsize=12)
plot.xticks(rotation='vertical')
plot.xlabel('Número de residentes')
plot.ylabel('País')
plot.show()

"""## **Categorização por registros de sintomas**"""

# Exibindo a quantidade de sintomas únicos. A quantidade é bastante expressiva 
# porque apesar do Flaredown possuir alguns sintomas pré-definidos, ele permite
# que o usuário insira um novo.
dataset[dataset.trackable_type=="Symptom"].trackable_name.nunique()

# Ranqueando os sintomas mais registrados
dataset[dataset.trackable_type=="Symptom"].trackable_name.value_counts().head(15)

# Impressão de um gráfico para visualizar a representatividade dos sintomas do dataset.
# Nota-se uma quantidade expressiva dos sintomas de dor de cabeça, fadiga e náusea.
plot.figure(figsize=(9,6))
symptoms = dataset[dataset.trackable_type=="Symptom"].trackable_name.value_counts().iloc[0:15]
sns.barplot(symptoms.values, symptoms.index)
for i, v in enumerate(symptoms.values):
    plot.text(0.8, i, v, color='k',fontsize=12)
plot.xticks(rotation='vertical')
plot.xlabel('Número de registros')
plot.ylabel('Sintoma')
plot.show()

"""## **Categorização por registros de tratamentos**

"""

# Exibindo a quantidade de tratamentos únicos. A quantidade é bastante expressiva porque 
# apesar do Flaredown possuir alguns tratamentos pré-definidos, ele permite que o
# usuário insira um novo.
dataset[dataset.trackable_type=="Treatment"].trackable_name.nunique()

# Ranqueando os tratamentos mais registrados
dataset[dataset.trackable_type=="Treatment"].trackable_name.value_counts().head(10)

# Impressão de um gráfico para visualizar a representatividade dos tratamentos do dataset.
# Nota-se uma quantidade expressiva na utilização do Ibuprofeno.
plot.figure(figsize=(9,6))
treatments = dataset[dataset.trackable_type=="Treatment"].trackable_name.value_counts().iloc[0:10]
sns.barplot(treatments.values, treatments.index)
for i, v in enumerate(treatments.values):
    plot.text(0.8, i, v, color='k',fontsize=12)
plot.xticks(rotation='vertical')
plot.xlabel('Número de registros')
plot.ylabel('Tratamento')
plot.show()

"""## **Categorização por registro de condição**"""

# Exibindo a quantidade de condições únicas. A quantidade é bastante expressiva porque 
# apesar do Flaredown possuir algumas condições pré-definidas, ele permite que o
# usuário insira uma nova.
dataset[dataset.trackable_type=="Condition"].trackable_name.nunique()

# Ranqueando as condições mais registradas
dataset[dataset.trackable_type=="Condition"].trackable_name.value_counts().head(10)

# Impressão de um gráfico para visualizar a representatividade das condições do dataset.
# Nota-se uma quantidade expressiva nas condições de Fibromialgia, Depressão e Ansiedade.
plot.figure(figsize=(9,6))
conditions = dataset[dataset.trackable_type=="Condition"].trackable_name.value_counts().iloc[0:10]
sns.barplot(conditions.values, conditions.index)
for i, v in enumerate(conditions.values):
    plot.text(0.8, i, v, color='k',fontsize=12)
plot.xticks(rotation='vertical')
plot.xlabel('Número de registros')
plot.ylabel('Condição')
plot.show()

"""# **ASSOCIAÇÃO**

"""

MAX_SYMPTOM_COLUMNS = 0
MAX_TREATMENT_COLUMNS = 20
MAX_ROWS = 200000

# Pré-processa o dataframe original
dfOrigin = pandas.DataFrame.copy(dataset)
dfOrigin['trackable_type'] = dfOrigin['trackable_type'].str.lower()
dfOrigin['trackable_name'] = dfOrigin['trackable_name'].str.lower()

# Conta as frequências dos sintomas e tratamentos, pega somente os mais frequentes para escolher os registros e as colunas
dfFrequentSymptoms = dfOrigin[dfOrigin['trackable_type'] == 'symptom']['trackable_name'].value_counts().rename_axis('trackable_name').reset_index(name = 'frequency').head(MAX_SYMPTOM_COLUMNS)
dfFrequentTreatments = dfOrigin[dfOrigin['trackable_type'] == 'treatment']['trackable_name'].value_counts().rename_axis('trackable_name').reset_index(name = 'frequency').head(MAX_TREATMENT_COLUMNS)

print(dfFrequentSymptoms)

# Pega registros que possuem sintoma frequente ou tratamento frequente
dfOrigin = dfOrigin[
		((dfOrigin['trackable_type'] == 'symptom') & (dfOrigin['trackable_name'].isin(dfFrequentSymptoms['trackable_name'].tolist()))) |
		((dfOrigin['trackable_type'] == 'treatment') & (dfOrigin['trackable_name'].isin(dfFrequentTreatments['trackable_name'].tolist())))
]

dfOrigin = dfOrigin.head(MAX_ROWS)

dfSymptoms = dfOrigin[dfOrigin['trackable_type'] == 'symptom']
dfTreatments = dfOrigin[dfOrigin['trackable_type'] == 'treatment']

print("Quantidade de Symptoms:", len(dfSymptoms.index))
print("Quantidade de Treatments:", len(dfTreatments.index))

# Cria as colunas do dataframe final
dfFinal = pandas.DataFrame({})

symptomColumnNames = ['symptom_' + s for s in dfFrequentSymptoms['trackable_name'].unique()]
treatmentColumnNames = ['treatment_' + t for t in dfFrequentTreatments['trackable_name'].unique()]

for symptomColumn in symptomColumnNames:
	dfFinal.insert(dfFinal.columns.size, symptomColumn, [])

for treatmentColumn in treatmentColumnNames:
	dfFinal.insert(dfFinal.columns.size, treatmentColumn, [])
 
dfGrouped = dfOrigin.groupby(['user_id', 'checkin_date'])

# Cria as linhas do dataframe final
for name, group in dfGrouped:
	newRow = pandas.DataFrame({})
 
	for column in dfFinal.columns:
		newRow.at[0, column] = False

	for index, row in group.iterrows():
		columnName = row['trackable_type'] + "_" + row['trackable_name']
		newRow.at[0, columnName] = True

	dfFinal = pandas.concat([dfFinal, newRow], ignore_index = True)

printBar()
print(dfFinal)
printBar()

# Aplicando algoritmo Apriori
rules = apriori(dfFinal, min_support = 0.01, use_colnames = True)
associationRules = association_rules(rules, metric = "confidence", min_threshold = 0.6)

print(rules)
printBar()
print(associationRules)